# Generated by Django 2.2 on 2021-10-30 07:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('helper', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='WorkCompletionForm',
            new_name='Borang',
        ),
    ]
